### ISSUE TITLE
tutorial 2 cifar10 training with DavidNet

### ISSUE THREAD

**Issue by fastalgo** [fenwickslab/fenwicks#1]
Dear Author,
You only have one step in the eval part?
The batch size of the eval part is 512.
So you only do the eval on 512 samples?
I think CIFAR10 has 10,000 samples for eval.

**Comment by fastalgo** [comment]
I tried increasing the eval steps, but the code crashed.

**Comment by yindavidyang** [comment]
The evaluation batch size here is the same as number of test samples (val_bs = n_test in the code below), which is 10,000. Therefore, there's only one eval step:

est = fw.train.get_tpu_estimator(steps_per_epoch, model_func,
  work_dir, trn_bs=BATCH_SIZE, val_bs=n_test)

If you increase the number of eval steps, the TPUEstimator raises an error (as expected), since we only have eval data for one step.

If you are looking for an example with multiple steps in the evaluation, please refer to Tutorial 3, which involves exactly the same model and dataset.
